/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Category = IDL.Variant({
  'locksmith' : IDL.Null,
  'cleaning' : IDL.Null,
  'other' : IDL.Null,
  'hvac' : IDL.Null,
  'plumbing' : IDL.Null,
  'painting' : IDL.Null,
  'electricity' : IDL.Null,
  'gardening' : IDL.Null,
  'renovations' : IDL.Null,
  'moving' : IDL.Null,
  'carpentry' : IDL.Null,
  'masonry' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserProfile = IDL.Record({
  'isWorker' : IDL.Bool,
  'name' : IDL.Text,
  'isClient' : IDL.Bool,
  'email' : IDL.Text,
});
export const Filter = IDL.Record({
  'country' : IDL.Opt(IDL.Text),
  'city' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(Category),
});
export const ListingData = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'active' : IDL.Bool,
  'country' : IDL.Text,
  'owner' : IDL.Principal,
  'city' : IDL.Text,
  'professionalName' : IDL.Text,
  'description' : IDL.Text,
  'mainImageId' : IDL.Text,
  'experienceYears' : IDL.Nat,
  'category' : Category,
  'price' : IDL.Text,
  'additionalImageIds' : IDL.Vec(ExternalBlob),
});
export const MessageData = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'read' : IDL.Bool,
  'recipient' : IDL.Principal,
  'sender' : IDL.Principal,
  'timestamp' : IDL.Int,
});
export const RatingData = IDL.Record({
  'id' : IDL.Nat,
  'listingId' : IDL.Nat,
  'comment' : IDL.Text,
  'timestamp' : IDL.Int,
  'rating' : IDL.Nat,
  'reviewer' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addRating' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [IDL.Int], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createListing' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        Category,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Vec(ExternalBlob),
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteListing' : IDL.Func([IDL.Nat], [], []),
  'getAverageRating' : IDL.Func([IDL.Nat], [IDL.Float64], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversations' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getListings' : IDL.Func(
      [IDL.Opt(Filter)],
      [IDL.Vec(ListingData)],
      ['query'],
    ),
  'getMessages' : IDL.Func([IDL.Principal], [IDL.Vec(MessageData)], ['query']),
  'getRatingsByListing' : IDL.Func([IDL.Nat], [IDL.Vec(RatingData)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markMessageAsRead' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'updateListing' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        Category,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Vec(ExternalBlob),
        IDL.Text,
        IDL.Bool,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Category = IDL.Variant({
    'locksmith' : IDL.Null,
    'cleaning' : IDL.Null,
    'other' : IDL.Null,
    'hvac' : IDL.Null,
    'plumbing' : IDL.Null,
    'painting' : IDL.Null,
    'electricity' : IDL.Null,
    'gardening' : IDL.Null,
    'renovations' : IDL.Null,
    'moving' : IDL.Null,
    'carpentry' : IDL.Null,
    'masonry' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserProfile = IDL.Record({
    'isWorker' : IDL.Bool,
    'name' : IDL.Text,
    'isClient' : IDL.Bool,
    'email' : IDL.Text,
  });
  const Filter = IDL.Record({
    'country' : IDL.Opt(IDL.Text),
    'city' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(Category),
  });
  const ListingData = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'active' : IDL.Bool,
    'country' : IDL.Text,
    'owner' : IDL.Principal,
    'city' : IDL.Text,
    'professionalName' : IDL.Text,
    'description' : IDL.Text,
    'mainImageId' : IDL.Text,
    'experienceYears' : IDL.Nat,
    'category' : Category,
    'price' : IDL.Text,
    'additionalImageIds' : IDL.Vec(ExternalBlob),
  });
  const MessageData = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'read' : IDL.Bool,
    'recipient' : IDL.Principal,
    'sender' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  const RatingData = IDL.Record({
    'id' : IDL.Nat,
    'listingId' : IDL.Nat,
    'comment' : IDL.Text,
    'timestamp' : IDL.Int,
    'rating' : IDL.Nat,
    'reviewer' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addRating' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [IDL.Int], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createListing' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          Category,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Vec(ExternalBlob),
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteListing' : IDL.Func([IDL.Nat], [], []),
    'getAverageRating' : IDL.Func([IDL.Nat], [IDL.Float64], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversations' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getListings' : IDL.Func(
        [IDL.Opt(Filter)],
        [IDL.Vec(ListingData)],
        ['query'],
      ),
    'getMessages' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(MessageData)],
        ['query'],
      ),
    'getRatingsByListing' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(RatingData)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markMessageAsRead' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'updateListing' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          Category,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Vec(ExternalBlob),
          IDL.Text,
          IDL.Bool,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };